task: detect
mode: train
model: /Users/prathamprabhu/Downloads/Githubclip-model-main/CLIP model copy/yolov8_project/runs/detect/yolov11_best_reproduction_20251223_095945/weights/best.pt
data: /Users/prathamprabhu/Downloads/Githubclip-model-main/CLIP model copy/yolov8_project/dataset_merged/data.yaml
epochs: 80
time: null
patience: 15
batch: 8
imgsz: 640
save: true
save_period: 5
cache: true
device: mps
workers: 4
project: /Users/prathamprabhu/Downloads/Githubclip-model-main/CLIP model copy/yolov8_project/runs/detect
name: phase2_toe_drain_optimized_20251223_113245
exist_ok: false
pretrained: true
optimizer: AdamW
verbose: true
seed: 0
deterministic: true
single_cls: false
rect: false
cos_lr: true
close_mosaic: 20
resume: false
amp: true
fraction: 1.0
profile: false
freeze: null
multi_scale: false
compile: false
overlap_mask: true
mask_ratio: 4
dropout: 0.0
val: true
split: val
save_json: false
conf: 0.25
iou: 0.7
max_det: 300
half: false
dnn: false
plots: true
source: null
vid_stride: 1
stream_buffer: false
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
embed: null
show: false
save_frames: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
show_boxes: true
line_width: null
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: true
opset: null
workspace: null
nms: false
lr0: 0.0001
lrf: 0.01
momentum: 0.937
weight_decay: 0.001
warmup_epochs: 3
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 10.0
cls: 0.6
dfl: 1.7
pose: 12.0
kobj: 1.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 5.0
translate: 0.1
scale: 0.6
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 0.2
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
copy_paste_mode: flip
auto_augment: randaugment
erasing: 0.4
cfg: null
tracker: botsort.yaml
save_dir: /Users/prathamprabhu/Downloads/Githubclip-model-main/CLIP model copy/yolov8_project/runs/detect/phase2_toe_drain_optimized_20251223_113245
